name: webitel_portal_sdk
description: Webitel Portal SDK.
version: 1.0.1

environment:
  sdk: ^3.3.3

dependencies:
  build_runner: ^2.4.9
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0+1
  retry: ^3.1.2
  fixnum: ^1.1.0
  logging: ^1.2.0
  injectable: ^2.4.1
  protobuf: ^3.1.0
  uuid: ^4.4.0
  grpc: ^3.2.4



dev_dependencies:
  lints: ^4.0.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2


